name: Electron Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Wine and dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install wine32
    - name: Install dependencies
      run: |
        npm install electron-builder -g
        npm install
    - name: Execute build.sh
      run: bash build.sh
