name: Electron Build

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Wine (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install wine --no-progress
    
    - name: Install Xcode (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        xcode-select --install

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm run build:win
        npm run build:mac
